# Generated by Django 4.2 on 2024-03-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-payment_method',), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
